# Log Configurations
# log:
#   level: info
#   forceColor: false
#   disableColor: false
#   alertHook: # Alert hooking settings
#     # Hooked logrus level for alert notification
#     level: warn
#     # Default notification channels
#     channels: []
#     # Maximum request timeout allowed to send alert.
#     SendTimeout: 3s
#     # Async worker options for sending alert
#     async:
#       # The number of worker goroutines (set `0` to turn off async mode).
#       numWorkers: 1
#       # The maximum number of queued jobs.
#       queueSize: 60
#       # Maximum timeout allowed to gracefully stop.
#       StopTimeout: 5s

# Alert Configurations
# alert:
#   # Custom tags are usually used to differentiate between different networks and enviroments
#   # such as mainnet/testnet, prod/test/dev or any custom info for more details.
#   customTags: [dev]
#   # Channels: Notification channels
#   # Key: Unique identifier for the channel (e.g., channel ID)
#   # Value: Configuration for the channel
#   channels:
#     dingrobot: # Example channel configuration for DingTalk
#       platform: dingtalk # Mandatory field indicating the channel type
#       webhook: https://oapi.dingtalk.com/robot/send?access_token=${your_access_token}
#       secret:  ${your_access_secret}
#       atMobiles: []
#       isAtAll: false
#     tgrobot: # Example channel configuration for Telegram
#       platform: telegram # Mandatory field indicating the channel type
#       apiToken:  ${your_api_token}
#       chatId: ${your_chat_id}

# REST API Configurations
# api:
#   endpoint: :12345
#   recoveryDisabled: false
#   corsOrigins: []
#   logger: false

# Metrics configurations
# metrics:
#   enabled: false
#   namespace:
#   reportInterval: 10s
#   influxdb:
#     host: http://127.0.0.1:8086
#     db: metrics_db
#     username:
#     password:

# Store Configurations
store:
  mysql:
#     host: 127.0.0.1:3306
#     username: root
    password:
    database: yourdbname
#     connMaxLifeTime: 3m
#     maxOpenConns: 10
#     maxIdleConns: 10
#     logLevel: warn
#     slowThreshold: 200ms
